# Generated by Django 4.2.7 on 2026-06-02 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatkada', '0002_alter_userprofile_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='max_users',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('stranger', 'Stranger Chat'), ('private_bench', 'Private Bench'), ('theatre', 'Theatre Room')], default='stranger', max_length=15),
        ),
        migrations.CreateModel(
            name='TheatreSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_seats', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='chatkada.chatroom')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('room', 'seat_number')},
            },
        ),
    ]
