# Generated by Django 4.2.7 on 2026-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatkada', '0003_alter_chatroom_max_users_alter_chatroom_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='channel_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
